### ISSUE TITLE
edx_sandbox playbook TASK: [edxapp | bundle install] fails with  Bundler::GemfileNotFound

### ISSUE THREAD

**Issue by ohss** [openedx-unsupported/configuration#2787]
Hi,

I'm following these instructions: [edX Ubuntu 12.04 64 bit Installation](https://github.com/edx/configuration/wiki/edX-Ubuntu-12.04-64-bit-Installation)

I have a 64bit Ubuntu 12.04.5 t2.medium instance running on AWS with 50GB storage. I've followed the instructions (only difference is that i used `export LC_ALL=C` to set locales), but running `sudo ansible-playbook -c local ./edx_sandbox.yml -i "localhost,"` fails with the following notice:

```
TASK: [edxapp | bundle install] *********************************************** 
failed: [localhost] => {"changed": true, "cmd": "bundle install --binstubs", "delta": "0:00:00.101771", "end": "2016-02-18 13:39:03.891146", "rc": 10, "start": "2016-02-18 13:39:03.789375", "warnings": []}
stdout: Bundler::GemfileNotFound

FATAL: all hosts have already failed -- aborting
```

Any ideas what's going wrong? I tried looking for gemfiles with `sudo find / -name "Gemfile"` but found nothing helpful.

Here's a [full trace](http://pastebin.com/eLe3g2yA) of running `cd /var/tmp/configuration/playbooks && sudo ansible-playbook -c local ./edx_sandbox.yml -i "localhost,"`

**Comment by nedbat** [comment]
This happens if you followed the manual instructions including setting the OPENEDX_RELEASE variable.  Unfortunately, these instructions were wrong.  Setting that variable doesn't work properly with the ansible playbooks.  I've updated the wiki page to make that clear.  Sorry for the trouble.

**Comment by jamesjohnson92** [comment]
i have unset the OPENEDX_VARIABLE, but still i get the same error 

failed: [localhost] => {"changed": true, "cmd": "bundle install --binstubs", "delta": "0:00:00.192986", "end": "2016-02-20 10:47:43.419805", "rc": 10, "start": "2016-02-20 10:47:43.226819", "warnings": []}
stdout: Bundler::GemfileNotFound

FATAL: all hosts have already failed -- aborting

Please tell me how to solve this?

**Comment by nedbat** [comment]
@jamesjohnson92 @ohss @DivyaMangotra If these were meant to be fresh installs, can you please try starting from the beginning again?  If it doesn't work, please provide details about what you did.  "I followed the instructions on the wiki page" isn't enough: there are choices and options there.

If you have ideas for edits that wiki page to make the instructions better, let's discuss them here.

**Comment by DivyaMangotra** [comment]
@nedbat @ohss I think I know why this happened, if you look at the edx_sandbox.yml in the branch **_"named-release/dogwood.rc_**" or "**_named-release/dogwood_**", the value of "**edx_platform_version**" is set to "**master**" whereas in the "**_roles/edxapp/defaults/main.yml_**" this value is set to "**release**". 
Also @feanil has removed all the Ruby dependencies in the edxapp role on February 9, 2016.
And things worked for me after  I removed the Ruby dependencies from edxapp role in dogwood and set the value of "edx_platform_version" as "named-release/dogwood.rc"

**Comment by nedbat** [comment]
This problem is now fixed.

**Comment by fghaas** [comment]
@nedbat, can you please reference the comment in which this was fixed? The referenced PR is still open.

**Comment by nedbat** [comment]
@fghaas that PR is in the edraak repo.  I thought the problem mentioned here was fixed by correcting the wiki page instructions.

**Comment by fghaas** [comment]
@nedbat, @jamesjohnson92 writes that the issue persisted even after he unset `OPENEDX_RELEASE`.  So if that's all the Wiki update covered, that wouldn't be sufficient. @DivyaMangotra highlights an issue with `edx_platform_version` in the playbooks as well; has _that_ been fixed?

**Comment by nedbat** [comment]
I'm not sure which scenarios we are talking about.  @DivyaMangotra mentions trying to install Dogwood.  @jamesjohnson92 mentions having no OPENEDX_RELEASE variable set, so I assume he wanted master?  I can test each of these.

@fghaas do you have an installation that is going wrong? We could use some more details here.

**Comment by fghaas** [comment]
I ran into this exact issue when experimenting with running the Open edX single node install in an LXC container, yes. I might be able to get back to that this week.

**Comment by nedbat** [comment]
@fghaas were you trying to install master, or Dogwood?

**Comment by fghaas** [comment]
`master`.

**Comment by nedbat** [comment]
Hmm, I just tried a native install of master, and it completed without a bundle problem at all.

**Comment by fghaas** [comment]
Well, my LXC install completed now, as well (modulo having to disable the AppArmor bits, of course — you can't modify AppArmor profiles from within an LXC container). Maybe a temporary fluke that prevented `gem install` for some time?

**Comment by nedbat** [comment]
Hmm, hard to say.  Anyone else who encounters this:  If you can provide a complete pastebin showing all the steps you took, that might help us catch this elusive beast. :)

**Comment by romain-li** [comment]
I have encountered the same problem.

I saw in this commit edX has deleted the Gemfile: https://github.com/edx/edx-platform/commit/f1b366589b67fa507592f875e9b225de55b149b4 (and this is the PR https://github.com/edx/edx-platform/pull/11470). But this file is still in the dogwood release.

That might be I haven't set the OPENEDX_RELEASE variable at the first time, and the second time I have set it to `named-release/dogwood.3`. It seems like I have passed this step.

**Comment by nedbat** [comment]
The Gemfile has been removed on master, after Dogwood, so Dogwood still uses it.  If you set the OPENEDX_RELEASE variable consistently, you will have no problems.

**Comment by kythanh** [comment]
Hi @nedbat 
I am trying to do fresh install Native OpenEdx on Ubuntu 12.04 64 bit and still facing same problem. I have set `$OPENEDX_RELEASE=named-release/dogwood.3` into bash file, but running `sudo ansible-playbook -c local ./edx_sandbox.yml -i "localhost," --limit @/root/edx_sandbox.retry` still got error below. Do you have any suggestion? 

I am following instructions from https://openedx.atlassian.net/wiki/display/OpenOPS/Native+Open+edX+Ubuntu+12.04+64+bit+Installation

```
If you want to install an Open edX release, such as Dogwood, just set the OPENEDX_RELEASE variable before running the scripts. For example: 
export OPENEDX_RELEASE=the-tag/you-want-to-install
wget https://raw.githubusercontent.com/edx/configuration/master/util/install/ansible-bootstrap.sh -O - | sudo bash
wget https://raw.githubusercontent.com/edx/configuration/$OPENEDX_RELEASE/util/install/sandbox.sh -O - | bash
```

```
failed: [localhost] => {"changed": true, "cmd": "bundle install --binstubs", "delta": "0:00:00.074045", "end": "2016-08-09 13:07:04.205664", "rc": 10, "start": "2016-08-09 13:07:04.131619", "warnings": []}
stdout: Bundler::GemfileNotFound

FATAL: all hosts have already failed -- aborting
```

**Comment by kythanh** [comment]
Hi @nedbat 
I just realised that the scripts on https://openedx.atlassian.net/wiki/display/OpenOPS/Native+Open+edX+Ubuntu+12.04+64+bit+Installation got a typo in URL. After using both `$OPENEDX_RELEASE` in scripts, all working fine now.

```
wget https://raw.githubusercontent.com/edx/configuration/$OPENEDX_RELEASE/util/install/ansible-bootstrap.sh -O - | sudo bash

wget https://raw.githubusercontent.com/edx/configuration/$OPENEDX_RELEASE/util/install/sandbox.sh -O - | bash
```

<img width="494" alt="screen shot 2016-08-09 at 8 26 34 pm" src="https://cloud.githubusercontent.com/assets/869405/17517902/bf241934-5e6f-11e6-822d-c67854ed24d1.png">

**Comment by nedbat** [comment]
@kythanh by "typo" you mean the first line should have `$OPENEDX_RELEASE` instead of `master`?

**Comment by kythanh** [comment]
@nedbat yes. 
<img width="956" alt="screen shot 2016-08-09 at 10 19 04 pm" src="https://cloud.githubusercontent.com/assets/869405/17521940/67d6d2c4-5e7f-11e6-99e9-5ec8e4aef45f.png">

**Comment by aditya9960** [comment]
@nedbat Hi Ned, I have done native installation. It was successful after certain manual error debugging.
But Now I can't see "edxapp" in /edx/app/ path.
Only following is shown at /edx/app/:
edx_ansible, nginx

How to fix this ?

**Comment by nedbat** [comment]
@aditya9960 this isn't a good place to get support.

**Comment by aditya9960** [comment]
Ok.

**Comment by OMKARdama12** [comment]
![screenshot from 2017-12-23 21-58-01](https://user-images.githubusercontent.com/31235010/34518635-336c13e0-f0a6-11e7-8d7b-945dc93c79c3.png)
how to solve this,any one can help me

**Comment by nedbat** [comment]
@OMKARdama12 we can't provide support in GitHub issues.
